
https://api.mysportsfeeds.com/v1.2/pull/nfl/current/daily_game_schedule.json?fordate=20200104
Authorization: Basic d9a32c89-be45-4a21-b331-6f0fe2 mys42sdE

###

https://api.mysportsfeeds.com/v1.2/pull/nhl/current/game_boxscore.json?gameid=47478
Authorization: Basic d9a32c89-be45-4a21-b331-6f0fe2 mys42sdE

###


https://api.mysportsfeeds.com/v1.2/pull/nfl/current/scoreboard.json?fordate=20190609
Authorization: Basic d9a32c89-be45-4a21-b331-6f0fe2 mys42sdE


